spring:
  application:
    name: cloud-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/comfort}
    username: ${DB_USER:comfort}
    password: ${DB_PASSWORD:comfort}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

  cloud:
    openfeign:
      client:
        config:
          openweather:
            url: https://api.openweathermap.org/data/2.5
            connect-timeout: 3000
            read-timeout: 5000
            logger-level: basic
            default-query-parameters:
              units: ["metric"]
              appid: ["${OPENWEATHER_API_KEY:}"]
              id: ["${OPENWEATHER_CITY_ID:3936456}"]   # Lima, PE

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.web: INFO
